"""add key, MS_account, proxy models

Revision ID: 0b929c33cca7
Revises: 1557f435774a
Create Date: 2025-10-20 10:42:16.826106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b929c33cca7'
down_revision: Union[str, Sequence[str], None] = '1557f435774a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_staff', sa.Boolean(), nullable=True))
    op.drop_column('users', 'is_stuff')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_stuff', sa.BOOLEAN(), nullable=True))
    op.drop_column('users', 'is_staff')
    # ### end Alembic commands ###
