"""add fields to users

Revision ID: 1557f435774a
Revises: 2a5db2f5f408
Create Date: 2025-09-28 10:24:46.928452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1557f435774a'
down_revision: Union[str, Sequence[str], None] = '2a5db2f5f408'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_stuff', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_stuff')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
