"""change column Ip in proxy

Revision ID: 3d104fbc10eb
Revises: 0b929c33cca7
Create Date: 2025-10-21 19:39:08.267890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d104fbc10eb'
down_revision: Union[str, Sequence[str], None] = '0b929c33cca7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proxies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('last_checked', sa.DateTime(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proxies_id'), 'proxies', ['id'], unique=False)
    op.create_table('MS_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('proxy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['proxy_id'], ['proxies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_MS_accounts_email'), 'MS_accounts', ['email'], unique=True)
    op.create_index(op.f('ix_MS_accounts_id'), 'MS_accounts', ['id'], unique=False)
    op.create_table('keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=25), nullable=True),
    sa.Column('checked', sa.Boolean(), nullable=True),
    sa.Column('is_activated', sa.Boolean(), nullable=True),
    sa.Column('redeemed_by', sa.String(), nullable=True),
    sa.Column('redeemed_date', sa.DateTime(), nullable=True),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keys_id'), 'keys', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_keys_id'), table_name='keys')
    op.drop_table('keys')
    op.drop_index(op.f('ix_MS_accounts_id'), table_name='MS_accounts')
    op.drop_index(op.f('ix_MS_accounts_email'), table_name='MS_accounts')
    op.drop_table('MS_accounts')
    op.drop_index(op.f('ix_proxies_id'), table_name='proxies')
    op.drop_table('proxies')
    # ### end Alembic commands ###
